Traceback (most recent call last):
  File "/Users/yurchisin/opt/anaconda3/envs/gurobi_ml/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/yurchisin/opt/anaconda3/envs/gurobi_ml/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yurchisin/opt/anaconda3/envs/gurobi_ml/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yurchisin/opt/anaconda3/envs/gurobi_ml/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/yurchisin/opt/anaconda3/envs/gurobi_ml/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/yurchisin/opt/anaconda3/envs/gurobi_ml/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/yurchisin/opt/anaconda3/envs/gurobi_ml/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%pip install -r requirements.txt              

import pandas as pd
import numpy as np
import math 


import gurobipy as gp
from gurobipy import GRB


#now hidden code
from setup_imports import *
------------------

----- stdout -----
[31mERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'[0m[31m
[0m
----- stdout -----
Note: you may need to restart the kernel to use updated packages.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 13[0m
[1;32m      9[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mgurobipy[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m GRB
[1;32m     12[0m [38;5;66;03m#now hidden code[39;00m
[0;32m---> 13[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01msetup_imports[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m [38;5;241m*[39m

[0;31mModuleNotFoundError[0m: No module named 'setup_imports'

